In [2]:
import stable_baselines3

In [3]:
from stable_baselines3 import PPO
from gym_pybullet_drones.envs.single_agent_rl import HoverIMU, HoverGPS, HoverFullState


pybullet build time: Sep 27 2023 23:43:15


In [4]:
agent = PPO(
    'MlpPolicy', 
    env=HoverIMU(),
    verbose=0,
    # tensorboard_log=exp_dir,
    # policy_kwargs=dict(net_arch=dict(pi=[64*model_scale, 64*model_scale], qf=[64*model_scale, 64*model_scale])),
    # n_steps=buffer_size,
    # batch_size=batch_size
)

<Element 'properties' at 0x7aa826ed0b30>
Frequency  1000


/home/led/miniconda3/lib/python3.11/site-packages/gymnasium/spaces/box.py:130: UserWarning: WARN: Box bound precision lowered by casting to float32
  gym.logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/led/miniconda3/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [16]:
import numpy as np
a = np.array([1., 2., 3.])
a

array([1., 2., 3.])

In [29]:
from scipy.spatial.transform import Rotation as R
import numpy as np

In [47]:
rot = R.from_euler("ZYX", np.array([0, 180, 0]), degrees=True)

In [48]:
rot.apply([0, 0, 1])

array([ 1.2246468e-16,  0.0000000e+00, -1.0000000e+00])

In [32]:
rot.as_matrix()

array([[ 1.11022302e-16, -1.00000000e+00, -1.11022302e-16],
       [ 8.66025404e-01,  1.11022302e-16, -5.00000000e-01],
       [ 5.00000000e-01,  0.00000000e+00,  8.66025404e-01]])

In [25]:
4*1.9571e-08*(24000**2)

45.091584

In [ ]:
def get_command(alpha, max_vel):
    new_pos = np.array([0, 0, 20])
    command = (np.random.rand(4)*2 - 1)*alpha
    command[0]=0
    rot = R.from_euler("ZYX", command[:3]*180, degrees=True)
    command[:3] = rot.apply([0, 0, 1])

    # command[3] *= self.drone.max_speed/(2-self.alpha)
    command[3] = max_vel*(0.5 + 0.5*command[3])
    return command

In [27]:
np.exp(-400)*200

3.830339193428011e-172

In [19]:
a *=2/3
a

array([0.66666667, 2.        , 3.33333333])

In [5]:
model_scale = 1
agent2 = PPO(
    'MlpPolicy', 
    env=HoverIMU(),
    verbose=0,
    # tensorboard_log=exp_dir,
    policy_kwargs=dict(net_arch=dict(pi=[64*model_scale, 64*model_scale], vf=[64*model_scale, 64*model_scale])),
    # n_steps=buffer_size,
    # batch_size=batch_size
)

<Element 'properties' at 0x7aa8273617b0>
Frequency  1000


/home/led/miniconda3/lib/python3.11/site-packages/gymnasium/spaces/box.py:130: UserWarning: WARN: Box bound precision lowered by casting to float32
  gym.logger.warn(f"Box bound precision lowered by casting to {self.dtype}")


In [6]:
agent.policy

ActorCriticPolicy(
  (features_extractor): FlattenExtractor(
    (flatten): Flatten(start_dim=1, end_dim=-1)
  )
  (pi_features_extractor): FlattenExtractor(
    (flatten): Flatten(start_dim=1, end_dim=-1)
  )
  (vf_features_extractor): FlattenExtractor(
    (flatten): Flatten(start_dim=1, end_dim=-1)
  )
  (mlp_extractor): MlpExtractor(
    (policy_net): Sequential(
      (0): Linear(in_features=7, out_features=64, bias=True)
      (1): Tanh()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): Tanh()
    )
    (value_net): Sequential(
      (0): Linear(in_features=7, out_features=64, bias=True)
      (1): Tanh()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): Tanh()
    )
  )
  (action_net): Linear(in_features=64, out_features=4, bias=True)
  (value_net): Linear(in_features=64, out_features=1, bias=True)
)

In [9]:
import numpy as np

In [12]:
np.int256

AttributeError: module 'numpy' has no attribute 'int256'

In [17]:
seed = np.random.randint(0, 65000)
np.random.seed(seed=seed)

In [7]:
agent2.policy

ActorCriticPolicy(
  (features_extractor): FlattenExtractor(
    (flatten): Flatten(start_dim=1, end_dim=-1)
  )
  (pi_features_extractor): FlattenExtractor(
    (flatten): Flatten(start_dim=1, end_dim=-1)
  )
  (vf_features_extractor): FlattenExtractor(
    (flatten): Flatten(start_dim=1, end_dim=-1)
  )
  (mlp_extractor): MlpExtractor(
    (policy_net): Sequential(
      (0): Linear(in_features=7, out_features=64, bias=True)
      (1): Tanh()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): Tanh()
    )
    (value_net): Sequential(
      (0): Linear(in_features=7, out_features=64, bias=True)
      (1): Tanh()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): Tanh()
    )
  )
  (action_net): Linear(in_features=64, out_features=4, bias=True)
  (value_net): Linear(in_features=64, out_features=1, bias=True)
)